### ISSUE TITLE
雨弓さん（@rain_vc）のガイドライン書き起こし

### ISSUE THREAD

**Issue by moyasine** [Bitcoin-Cash-JP/guidelines#4]
このツイートの画像の文字を起こしてもらう
https://twitter.com/rain_vc/status/956515965600129024

**Comment by Ameyumi** [comment]
☆BitcoinCash(BCH)で決済するためにはまず、そして唯一**Wallet**(お財布)が必要です。

・WalletはbitFlyerやCoincheckなどの日本の取引所のものでも問題ありませんが、経理処理の関係も考えてブラウザ型の【**BLOCKCHAIN**】か、アプリ型の【**Bitcoin.com**】のWalletが知名度も高く作成しやすいためおススメです。
・Walletの作成の仕方はブログなどで簡単に紹介されています。

☆Walletを作成したら、支払いのルール作りをします。現状では特に法律などもないため(そもそも『BCH決済』ではなく、『BCH送金』を支払いとしているだけ)お店側で以下を決めます。
・送金用アドレスについて(URL or QRコード)
・支払い時のレート
・支払い内容、タイミング

☆送金用アドレスについては圧倒的に**QRコード**をオススメします。
・QRコードはレジ横などに紙で何枚か印刷しておくと会計時のBCH決済がスムーズかと思います。
・URL入力はコピー&ペーストでのミスを招きやすく、またそれをお客様に伝えるのも手間です。
・お客様がQRコード認証できない時のみTwitterのDMやLINEなどでURLを送るのが良いかと思います。

☆レートに関しても法律は特にありませんが、しっかりとお店のルールは決めておかないとトラブルになる可能性があります。

【固定レート】1日の始値やオープン時に『今日は1BCH=20万円』と設定します。お客様は会計の計算がしやすく安心できます。現状はコチラがオススメです。

【変動レート】会計時に取引所やWalletの価格から算出します。仮想通貨っぽくて面白いですが、ボラティリティが激しいため注意が必要です(例：入店後に暴落し、用意していたBCHが足りなくなる…など)。

☆支払い内容とタイミングについてですが、BCH決済は会計時に合計金額を『円からBCHに計算するやり方』と、商品それぞれにBCHの値段をつけて会計時に合計する方法があります。
・商品数にもよりますが、ボラティリティが高い現状では基本的に『円で計算し、BCHに変換する』という方法がベストだと思います。
・また、支払いのタイミングですが飲食店であればお店を出る10分前程度にBCH決済を済ませると退店時までに着金もほぼ完了する(ブロックで承認される)ため、とてもスマートです。 (決済して数秒で店舗側のWalletに通知自体はいきます)

☆ざっくりと要点だけまとめて作成しました。
・まだまだ改善点などあると思いますのでどんどん意見をお聞かせください。
・実際に導入している店舗様で不便な点や「こんなアプリがあったら便利なのに！」　という事をぜひ教えてください。
・作者：雨弓(Twitter ID: rain_vc)

**Comment by moyasine** [comment]
雨弓さんありがとうございます！
中立性を担保したいので、この文章をそのまま使うということはできませんが
GitBook下部にContributer（寄与していただいた方）という欄を設けてそこにIDと名前を書こうと思っています。

**Comment by Ameyumi** [comment]
もやしんさん

了解です！
よろしくお願いします(´･ω･｀)

2018年1月31日(水) 12:37 moyasine <notifications@github.com>:
